# YunForge Lab 网站基础配置

# GitHub Pages 网站地址
baseurl = "https://luyunhong12.github.io/"

# 网站语言区域
locale = "zh-cn"

# 网站名称
title = "YunForge Lab"

# 默认内容语言
defaultContentLanguage = "zh-cn"

# 开启中文、日文、韩文的正确摘要和字数统计
hasCJKLanguage = true

# 暂时关闭 Disqus 评论
disqusShortname = ""

# 首页每页显示5篇文章
[pagination]
    pagerSize = 5
